language: R
cache: packages

r_github_packages:
  - jimhester/covr
  - r-lib/testthat

r:
  - release
  - devel
  - oldrel
bioc_packages: GenomicRanges
bioc_packages: InteractionSet

# Upload CodeCov information
after_success:
  - Rscript -e 'covr::codecov()'