sudo: false
language: R
cache: packages

r_github_packages:
  - r-lib/testthat
  
r_packages:
  - covr
  
r:
  - release
  - devel
  - oldrel

bioc_packages: 
  - GenomicRanges
  - InteractionSet

# Upload CodeCov information
after_success:
  - Rscript -e 'library(covr); codecov()'
